// 41 HTC species — alphabetical order
export const SPECIES_LIST: string[] = [
  "Aleppo Pine",
  "Ash Species",
  "Avocado Tree",
  "Blue Gum",
  "Bottlebrush",
  "Bradford Callery Pear",
  "Brazilian Pepper Tree",
  "Bronze Loquat",
  "California Pepper Tree",
  "California Sycamore",
  "Camphor Tree",
  "Canary Island Pine",
  "Carob Tree",
  "Carrotwood",
  "Chinese Elm",
  "Coral Tree",
  "Crape Myrtle",
  "Evergreen Pear",
  "Gold Medallion Tree",
  "Hollywood Juniper",
  "Hong Kong Orchid Tree",
  "Jacaranda",
  "Koelreuteria Species",
  "Lemon-Scented Gum",
  "Leyland Cypress",
  "Liquidambar",
  "Magnolia Species",
  "Mexican Fan Palm",
  "Monterey Pine",
  "Red Flowering Gum",
  "Red Maple",
  "Rubber Fig",
  "Shiny Xylosma",
  "Silk Oak",
  "Silver Dollar Tree",
  "Stone Pine",
  "Strawberry Tree",
  "Tipu",
  "Tristania",
  "Tupidanthus",
  "Weeping Fig",
];
